# Generated by Django 4.0.4 on 2022-06-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpQuali2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=30)),
                ('hsc', models.IntegerField()),
                ('ssc', models.IntegerField()),
                ('grad', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empapp.emp')),
            ],
            options={
                'db_table': 'emp_qualif2',
            },
        ),
    ]
