# Generated by Django 4.0.4 on 2022-06-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_empquali2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpQuali3',
            fields=[
                ('emp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empapp.emp')),
                ('college', models.CharField(max_length=30)),
                ('hsc', models.IntegerField()),
                ('ssc', models.IntegerField()),
                ('grad', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'emp_qualif3',
            },
            bases=('empapp.emp',),
        ),
    ]
