# Generated by Django 4.0.4 on 2022-06-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_singers_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='singer_sons',
            new_name='singer_songs',
        ),
    ]
