# Generated by Django 4.0.4 on 2022-06-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_rename_name_songs_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs2',
            fields=[
                ('singers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empapp.singers')),
                ('names', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'Songs2',
            },
            bases=('empapp.singers',),
        ),
    ]
