# Generated by Django 4.1 on 2022-08-14 18:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_delete_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Age', models.IntegerField()),
                ('Contact', models.IntegerField()),
                ('Country', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'RegsiterData',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
