# Generated by Django 4.1 on 2022-08-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter the Name', max_length=50)),
                ('Email', models.EmailField(max_length=60)),
                ('Phone', models.IntegerField(help_text='Enter the 10 digit Phone No.')),
                ('Username', models.CharField(max_length=15)),
                ('Password', models.CharField(help_text='Alpha & Numeric password', max_length=10)),
            ],
        ),
    ]
