# Generated by Django 4.1 on 2022-08-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Email',
            field=models.CharField(error_messages='please enter the gmail', max_length=60),
        ),
        migrations.AlterField(
            model_name='register',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='Phone',
            field=models.CharField(help_text='Enter the 10 digit Phone Number', max_length=11),
        ),
    ]
