# Generated by Django 4.1 on 2022-08-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Phone',
            field=models.IntegerField(max_length=11),
        ),
    ]
