# Generated by Django 4.1 on 2022-08-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0002_addnotes_add_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addnotes',
            old_name='add_by',
            new_name='user',
        ),
    ]
