# Generated by Django 4.0.4 on 2022-07-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('salary', models.IntegerField(max_length=10)),
            ],
        ),
    ]
