# Generated by Django 4.0.4 on 2022-07-18 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ormsql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
