# Generated by Django 4.0.4 on 2022-07-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormsql', '0002_userdetail_status_alter_userdetail_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='status',
        ),
    ]
