# Generated by Django 4.0.4 on 2022-07-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=30)),
                ('Age', models.IntegerField(max_length=2)),
                ('Contact', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
