# Generated by Django 4.0.4 on 2022-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_empregister_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregister',
            name='Age',
            field=models.IntegerField(max_length=10),
        ),
    ]
