# Generated by Django 4.0.4 on 2022-07-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_empregister_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=30)),
                ('Contact', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Userdata',
            },
        ),
    ]
