# Generated by Django 4.0.4 on 2022-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Contact',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Email',
            field=models.TextField(max_length=100),
        ),
    ]
