# Generated by Django 4.0.4 on 2022-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userdata_contact_alter_userdata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailValid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.CharField(max_length=200)),
            ],
        ),
    ]
