# Generated by Django 4.0.4 on 2022-06-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('skill', models.TextField(max_length=200)),
                ('experiance', models.CharField(max_length=30)),
                ('hsc', models.IntegerField(max_length=10)),
                ('ssc', models.IntegerField(max_length=10)),
                ('gradue', models.IntegerField(max_length=10)),
                ('hobby', models.TextField(max_length=200)),
            ],
        ),
    ]
