# Generated by Django 4.0.4 on 2022-08-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('JobTitle', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=256)),
                ('Phone', models.IntegerField()),
                ('JoinDate', models.DateField()),
                ('ProfileImage', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ProductData',
            },
        ),
    ]
