# Generated by Django 4.0.4 on 2022-08-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiIntergration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='ProfileImage',
            field=models.CharField(max_length=2000),
        ),
    ]
