# Generated by Django 4.0.4 on 2022-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=10)),
                ('add', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'pitent_appoint',
            },
        ),
    ]
