# Generated by Django 4.0.4 on 2022-07-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
