# Generated by Django 4.0.4 on 2022-07-19 16:13

from django.db import migrations, models
import valid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, validators=[valid.models.Namevalid])),
            ],
        ),
    ]
