# Generated by Django 4.0.4 on 2022-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=30)),
                ('join_date', models.DateField()),
                ('Department', models.CharField(max_length=30)),
                ('avtar_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'EmployeeData',
            },
        ),
    ]
