# Generated by Django 4.0.4 on 2022-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='empid',
            field=models.IntegerField(auto_created=True),
        ),
    ]
