# Generated by Django 4.0.4 on 2022-08-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0002_alter_employeedata_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata',
            name='empid',
        ),
    ]
