# Generated by Django 4.0.4 on 2022-06-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Contact', models.IntegerField(max_length=10)),
                ('Address', models.TextField(max_length=500)),
                ('Linkedin', models.CharField(max_length=200)),
                ('Github', models.CharField(max_length=200)),
                ('skill', models.TextField(max_length=300)),
                ('ssc', models.IntegerField()),
                ('hsc', models.IntegerField()),
                ('graud', models.IntegerField()),
                ('certification', models.TextField(max_length=500)),
                ('Lang', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'ResumeCheck',
            },
        ),
    ]
