# Generated by Django 4.0.4 on 2022-07-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Gender',
            field=models.CharField(max_length=8),
        ),
    ]
